#!/bin/bash

## this will retrieve all of the .go files that have been
## changed since the last commit
STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.go')

## we can check to see if this is empty
if [[ $STAGED_GO_FILES != "" ]]; then
    if ! command -v goimports &> /dev/null; then
        go install golang.org/x/tools/cmd/goimports@latest
    fi

    for file in $STAGED_GO_FILES; do
        # in the unlikly case someone doesn't have their editor setup
        gofmt -w -s $file
        exit_code=$?
        if [ $exit_code -ne 0 ]; then
            echo "Could not format your code: $exit_code."
            exit $exit_code
        fi

        ## regroup imports and format the file
        goimports -w $file
        exit_code=$?
        if [ $exit_code -ne 0 ]; then
            echo "Could reorder your imports: $exit_code."
            exit $exit_code
        fi

        ## add any potential changes from our formatting to the
        ## commit
        git add $file
    done

    # -j4 run all in parallel
    make -j4 precommit || { echo 'make precommit failed!' ; exit 1; }
fi
